# ===============================
# JoeyLLM Training Config
# ===============================

defaults:
  - _self_

# -------------------------------
# WandB Config
# -------------------------------

wandbconfig:
  project: JoeyLLM_Data
  name: Low LR
  mode: offline # "online", "offline", or "disabled"

# -------------------------------
# Dataset Config
# -------------------------------

dataconfig:
  data_path: data/008_00000.parquet
  batch_size: 16
  num_workers: 3
  shuffle: False     
  drop_last: True
  pin_memory: True  

# -------------------------------
# Model Config
# -------------------------------

modelconfig:
  vocab_size: 32000
  max_seq_len: 512
  embed_dim: 1280
  num_layers: 36
  num_heads: 20
  dropout: 0.1


# -------------------------------
# Optimizer Config
# -------------------------------

optimizerconfig:
  lr: 3e-4
  betas: [0.9, 0.95]
  weight_decay: 0.1

# -------------------------------
# Trainer Config
# -------------------------------

trainconfig:
  total_steps: 24235
  epochs: 3
  accumulation_steps: 4
  save_model_path: data/a100model2.pt
  log_freq: 1000

# -------------------------------
# Scheduler Config
# -------------------------------

schedulerconfig:
  max_lr: 4e-4
  pct_start: 0.01
  anneal_strategy: cos
  div_factor: 25.0
  final_div_factor: 10000.0
  cycle_momentum: true
  base_momentum: 0.85
  max_momentum: 0.95
  three_phase: false



