# ===============================
# JoeyLLM Training Config
# ===============================

defaults:
  - _self_

# -------------------------------
# WandB Config
# -------------------------------

wandbconfig:
  project: JoeyLLM
  name: Sunday
  mode: disabled # "online", "offline", or "disabled"

# -------------------------------
# Dataset Config
# -------------------------------

dataconfig:
  data_path: sample/10BT
  chunk_size: 512
  buffer_text_size: 8000
  batch_size: 16
  num_workers: 3
  tokenizer_path: SouthernCrossAI/JoeyLLM_Tokenizer
  dataset_name: HuggingFaceFW/fineweb
  shuffle_min_buffer: 10000
  shuffle_buffer_multiplier: 5
  pin_memory: true
  use_fast_tokenizer: true
  streaming: true

# -------------------------------
# Model Config
# -------------------------------

modelconfig:
  vocab_size: 32000
  max_seq_len: 512
  embed_dim: 768
  num_layers: 24
  num_heads: 16
  dropout: 0.1


# -------------------------------
# Optimizer Config
# -------------------------------

optimizerconfig:
  lr: 3e-4
  betas: [0.9, 0.95]
  weight_decay: 0.1

# -------------------------------
# Scheduler Config
# -------------------------------

schedulerconfig:
  max_lr: 4e-4
  pct_start: 0.01
  anneal_strategy: cos
  div_factor: 25.0
  final_div_factor: 10000.0
  cycle_momentum: true
  base_momentum: 0.85
  max_momentum: 0.95
  three_phase: false

# -------------------------------
# Trainer Config
# -------------------------------

trainconfig:
  total_steps: 400000
  epochs: 5
  accumulation_steps: 4
  save_model_path: model/a100model2.pt
  log_freq: 1000
  non_blocking: true


