# ===============================
# JoeyLLM Training Config
# ===============================

defaults:
  - _self_

# -------------------------------
# WandB Config
# -------------------------------

wandbconfig:
  project: JoeyLLM_Data
  name: Low LR
  mode: offline # "online", "offline", or "disabled"

# -------------------------------
# Dataset Config
# -------------------------------

dataconfig:
  data_path: sample/10BT
  chunk_size: 512
  buffer_text_size: 8000
  batch_size: 8 
  num_workers: 3

# -------------------------------
# Model Config
# -------------------------------

modelconfig:
  vocab_size: 32000
  max_seq_len: 512
  embed_dim: 1280
  num_layers: 36
  num_heads: 20
  dropout: 0.1


# -------------------------------
# Optimizer Config
# -------------------------------

optimizerconfig:
  lr: 3e-4
  betas: [0.9, 0.95]
  weight_decay: 0.1

# -------------------------------
# Trainer Config
# -------------------------------

trainconfig:
  total_steps: 24235
  epochs: 3

